// generated by gen-mocks; DO NOT EDIT

package mockstore

import (
	"golang.org/x/net/context"
	"sourcegraph.com/sourcegraph/sourcegraph/api/sourcegraph"
	"sourcegraph.com/sourcegraph/sourcegraph/pkg/store"
)

type BlacklistedSessionTokens struct {
	PersistBlacklistedToken_    func(ctx context.Context, user int32, token string) (r *sourcegraph.BlacklistResponse, err error)
	CheckSessionTokenBlacklist_ func(ctx context.Context, user int32, token string) (r *sourcegraph.BlacklistCheckResponse, err error)
}

func (s *BlacklistedSessionTokens) PersistBlacklistedToken(ctx context.Context, user int32, token string) (r *sourcegraph.BlacklistResponse, err error) {
	return s.PersistBlacklistedToken_(ctx, user, token)
}

func (s *BlacklistedSessionTokens) CheckSessionTokenBlacklist(ctx context.Context, user int32, token string) (r *sourcegraph.BlacklistCheckResponse, err error) {
	return s.CheckSessionTokenBlacklist_(ctx, user, token)
}

var _ store.BlacklistedSessionTokens = (*BlacklistedSessionTokens)(nil)
